name: "Release gdrive-datastore"
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: ${{ github.repository_owner}}
      REPO_BRANCH: ${{ github.ref_name }}
      SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
      GDRIVE_FOLDER: ${{ vars.GDRIVE_FOLDER }}
    steps:
    - uses: actions/checkout@v3
    - run: "python -m pip install -r requirements.txt"
    - run: "python -m pip install ."
    - run: "pytest tests"
    - shell: 'python'
      run: |
        import os
        # TODO: create .pypirc
        HOME = os.getenv('HOME','')
        filepath = f'{HOME}/.pypirc'
        print(filepath)
    - run: "python -m build"
    - run: "pytest tests"
    - run: "python -m twine upload --repository testpypi dist/*"


